{% set name = "DASPy-toolbox" %}
{% set version = "1.2.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: 8a4d2184eb4f4dff692e7e3662b25ab429bbecc7a7a1f46dd4b385c48836ceba

build:
  entry_points:
    - daspy = daspy.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.13
    - matplotlib-base
    - geographiclib
    - pyproj
    - h5py
    - segyio
    - nptdms
    - tqdm

test:
  imports:
    - daspy
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/HMZ-03/DASPy
  summary: DASPy is an open-source project dedicated to provide a python package for DAS (Distributed Acoustic Sensing) data processing, which comprises classic seismic data processing techniques and Specialized algorithms for DAS applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HMZ-03
